wso2_auth_check.settings:
  type: config_object
  label: 'WSO2 Auth Check settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable automatic authentication check'
    check_interval:
      type: float
      label: 'Check interval (minutes)'
    debug:
      type: boolean
      label: 'Enable debug mode'
