wso2_auth.settings:
  type: config_object
  label: 'WSO2 Authentication settings'
  mapping:
    # General Settings
    enabled:
      type: boolean
      label: 'Enable WSO2 Authentication'
    stage:
      type: boolean
      label: 'Use staging environment'
    skip_ssl_verification:
      type: boolean
      label: 'Skip SSL verification'
    ag_entity_id:
      type: string
      label: 'Entity ID (agEntityId)'
    com_entity_id:
      type: string
      label: 'Entity ID (comEntityId)'
    citizen_enabled:
      type: boolean
      label: 'Enable citizen authentication button'
    picture_enabled:
      type: boolean
      label: 'Enable picture on login form'
    auto_login:
      type: boolean
      label: 'Enable auto-login (Single Sign-On)'
    debug:
      type: boolean
      label: 'Enable debug mode'
    auth_server_url:
      type: string
      label: 'Authentication server URL'
    check_session_url:
      type: string
      label: 'URL per il controllo della sessione'
    external_domains_whitelist:
      type: string
      label: 'External domains whitelist for redirects'

    # Citizen Settings
    citizen:
      type: mapping
      label: 'Citizen authentication settings'
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client Secret'
        scope:
          type: string
          label: 'Scope'
        auto_register:
          type: boolean
          label: 'Auto-register users'
        user_role:
          type: string
          label: 'Role assigned to registered user'
        roles_to_exclude:
          type: sequence
          label: 'Roles to check'
          sequence:
            type: string
            label: 'Role'
        mapping:
          type: mapping
          label: 'Field mappings'
          mapping:
            username:
              type: string
              label: 'Username field'
            email:
              type: string
              label: 'Email field'
            first_name:
              type: string
              label: 'First name field'
            last_name:
              type: string
              label: 'Last name field'
            user_id:
              type: string
              label: 'User ID field'
            fiscal_code:
              type: string
              label: 'Fiscal code field'
            mobile_phone:
              type: string
              label: 'Mobile phone field'

    # Operator Settings
    operator:
      type: mapping
      label: 'Operator authentication settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable operator authentication'
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        scope:
          type: string
          label: 'Scope'
        ag_entity_id:
          type: string
          label: 'Entity ID (agEntityId)'
        ente:
          type: string
          label: 'Entity code'
        app:
          type: string
          label: 'Application code'
        username:
          type: string
          label: 'JWT username'
        password:
          type: string
          label: 'JWT password'
        role_population:
          type: string
          label: 'Role population rules'
        auto_register:
          type: boolean
          label: 'Auto-register users'
        user_role:
          type: string
          label: 'Default role'
        privileges_url:
          type: string
          label: 'Privileges service URL'
        privileges_stage_url:
          type: string
          label: 'Privileges service staging URL'
